---
  - name: Add PostgreSQL official APT repository
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
      # repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" #deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
      state: present
    tags: repo, postgres_deploy

  - name: Adding APT repository key
    become: yes
    apt_key:
      id: ACCC4CF8
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    tags: repo, postgres_deploy

  - name: Install Postgresql
    package:
      pkg: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - libpq-dev
      - python-psycopg2
      - "postgresql-{{ postgresql.version }}"
    tags: postgres_deploy

  - name: Copy DB config
    template:
      src: pg_hba.conf.j2
      dest: /etc/postgresql/{{postgresql.version}}/main/pg_hba.conf
    tags: postgres_deploy

  - name: Start PostgreSQL service
    service:
      name: postgresql
      state: restarted
    tags: postgres_deploy

  - name: Create a new database with name {{ item }}
    postgresql_db:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ postgresql.db_name }}"
    tags: postgres_deploy

  - name: Create user {{ db_user }}, and grant access
    postgresql_user:
      db: "{{ item }}"
      name: "{{ postgresql.db_user }}"
      password: "{{ postgresql.db_password }}"
      priv: "ALL"
      role_attr_flags: CREATEDB
    with_items:
      - "{{ postgresql.db_name }}"
    notify: Restart postgress
    tags: postgres_deploy